name: Eirik Norman Hansen
favicon: null
layout_spectrum: 0.47412
typography_spectrum: 0.15671
title: Eirik Norman Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75615265-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121013'
    - '#484743'
    - '#d8781c'
    - '#ffe06e'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
