name: eiriknorman
favicon: null
layout_spectrum: 0.11360754165798426
typography_spectrum: 0.4304314337205142
title: eiriknorman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5024432411883026
  lightness: 0.13696464244276285
  saturation: 0.5791530241258442
  rhythmicContrast: 0.0641984804533422
purpose: []
