name: Eirik Norman Hansen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15671
title: Eirik Norman Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c69df'
    - '#070707'
    - '#c4cfe5'
    - '#4e4037'
    - '#6126e4'
  brandStrength: 0.8125
  lightness: 0.13696464244276285
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
